/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `todos.todos`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `todos`;
CREATE TABLE `todos` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `date` DATETIME,
    `description` LONGTEXT,
    `done` BIT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `todos` (`__v`, `_id`, `date`, `description`, `done`)
    VALUES
        (0, x'5BB79B284EA748128C8B629E', '2018-10-06 00:00:00.000000', 'Type anything into column A to complete an item', TRUE);
INSERT INTO `todos` (`__v`, `_id`, `date`, `description`, `done`)
    VALUES
        (0, x'5BB79E82BAEE251CC86AFFCE', '2018-10-06 00:00:00.000000', 'Change the styling of completed items under ''Format'' > ''Conditional Formatting'' (on the web)', TRUE);
INSERT INTO `todos` (`__v`, `_id`, `date`, `description`, `done`)
    VALUES
        (0, x'5BB79E8BBAEE251CC86AFFCF', '2018-10-07 00:00:00.000000', 'Sort items using the drop-down arrows next to the heading name (on the web)', FALSE);
